spring:
  application:
    name: notification-service
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 27f352043d9a00
    password: 4e8888235485c4
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9094
    properties:
      schema.registry.url: http://localhost:8085
      specific.avro.reader: true
    consumer:
      group-id: notificationService
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer